# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9395f69bb0d21dd2c9d560309084101703895d2fda810d0308d88ace86dec46a43aa5ddd8925ed853aa9d0779116d39c7fa12f54964fa5e77cc436a3d6f5780

test:
  secret_key_base: 701a9354ebae20483ff81b3b40c1051b7e9562abc80a00354f748ee4381afe78989c62b979d4bf26a1cba56fbe1c905df93cd61d49768c268e28a13f110b5f9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
